export const ClientCodes = {
  CLIENT_VERSION_NOT_FOUND: 'CLIENT_VERSION_NOT_FOUND',
  NO_CLIENT_VERSIONS_AVAILABLE: 'NO_CLIENT_VERSIONS_AVAILABLE',
  CLIENT_VERSION_RETRIEVED: 'CLIENT_VERSION_RETRIEVED',
  CLIENT_VERSION_CREATED: 'CLIENT_VERSION_CREATED',
  CLIENT_VERSION_UPDATED: 'CLIENT_VERSION_UPDATED',

  CLIENT_LIBRARIES_RETRIEVED: 'CLIENT_LIBRARIES_RETRIEVED',

  INSTANCE_NOT_FOUND: 'INSTANCE_NOT_FOUND',
  INSTANCE_RETRIEVED: 'INSTANCE_RETRIEVED',
  INSTANCE_CREATED: 'INSTANCE_CREATED',
  INSTANCE_UPDATED: 'INSTANCE_UPDATED',

  LIBRARY_NOT_FOUND: 'LIBRARY_NOT_FOUND',
  LIBRARY_CREATED: 'LIBRARY_CREATED',
  LIBRARY_UPDATED: 'LIBRARY_UPDATED',
  LIBRARY_ADDED_TO_CLIENT: 'LIBRARY_ADDED_TO_CLIENT',
  LIBRARY_REMOVED_FROM_CLIENT: 'LIBRARY_REMOVED_FROM_CLIENT',

  PLUGIN_NOT_FOUND: 'PLUGIN_NOT_FOUND',
  PLUGIN_CREATED: 'PLUGIN_CREATED',
  PLUGIN_UPDATED: 'PLUGIN_UPDATED',

  MANIFEST_RETRIEVED: 'MANIFEST_RETRIEVED',
} as const;
